android_library(
    name = "news_fetch",
    custom_package = "io.github.izzyleung",
    srcs = glob(["src/main/java/io/github/izzyleung/**/*.java"]),
    deps = [
        "//proto:zhihu_daily_purify_java_proto",
        "//third_party:news_fetch_dependencies",
    ],
)